# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

APP_WORKSPACE = "SetupProject.xcworkspace"

TEST_DEVICES = ["iPhone 11"]

default_platform(:ios)

platform :ios do
  desc "Run iOS unit tests"
  lane :unit_tests do
      run_tests(
	  workspace: APP_WORKSPACE,
	  devices: TEST_DEVICES,
	  derived_data_path: "../build",
	  build_for_testing: true
      )
  end
  
  desc "Run linting"
  lane :lint do
     SWIFTLINT_EXECUTABLE = './Pods/SwiftLint/swiftlint'

     swiftlint(
       executable: SWIFTLINT_EXECUTABLE,
       mode: lint
     )
  end
end
