# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :lint do

    SWIFTLINT_YML_PATH = '/Users/iliyan.ivanov/Desktop/SetupProject/.swiftlint.yml'
    SWIFTLINT_EXECUTABLE = '/Users/iliyan.ivanov/Desktop/SetupProject/Pods/SwiftLint/swiftlint'
 
    swiftlint(
        executable: SWIFTLINT_EXECUTABLE,
	config_file: SWIFTLINT_YML_PATH 
    )
end

lane :tests do
   run_tests(
     workspace: 'SetupProject.xcworkspace',
     devices: ['iPhone 12'],
     scheme: 'SetupProject'
   )
end

lane :upload_to_firebase do 

    FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = "xsxr-bbjq-fkhw-ytjt"
    FIREBASE_TOKEN = "1//03X0qLuMs5GpbCgYIARAAGAMSNwF-L9IrW-U3883o0WVrWDlu29AeBkkYfqXD5dzp48oMDl6EVwQdcq303eUyUwG94l3kMWpzh7A"
  # set_info_plist_value(
  #  path: INFO_PLIST_PATH, 
  #   key: "CFBundleShortVersionString", 
  #   value: APP_VERSION
  # )
    clear_derived_data

    sigh(
      app_identifier: "com.upnetix.SetupProject",
      username: "iliyan.ivanov@scalefocus.com",
      team_id: "UWBDU93DZY",
      filename: "SetupProjectadHoc-2.mobileprovision"
    )

    gym(
      export_method: "ad-hoc",
      scheme: "SetupProject",
      workspace: "/Users/iliyan.ivanov/Desktop/SetupProject/SetupProject.xcworkspace",
      configuration: "Release",
      clean: true,
      codesigning_identity: "iPhone Distribution"
    )


    firebase_app_distribution(
      app: "1:930244491014:ios:ab7af8ce5f24844c08d087",
      firebase_cli_token: FIREBASE_TOKEN,
      testers: "iliyan.ivanov@scalefocus.com",
      groups: "testers-group",
      release_notes: "Special for my homo testers :D :D :D",
      firebase_cli_path: “/usr/local/bin/firebase”
    )
end